### ISSUE TITLE
What were the main reasons to move from 'libcoap' to your own 'coapcmd'?

### ISSUE THREAD

**Issue by axello** [moroen/coapcmd#3]
For a seemingly small utility module, people with embedded systems have to install a 258 MB golang compiler, to compile the coapcmd module. While there are several open source python coap libraries available and all the rest of the code is in python. 
What was your main reason to drop libcoap and implement a go library?
Stability?

**Comment by moroen** [comment]
The only python coap library that I've found with support for DTLS with preshared ident/key pairs, is aiocoap, which relies on DTLSSocket, which is next to impossible to install on windows. libcoap with tinydtls requires it own sets of hoops to jump through to get installed, with dependencies on among others, openssl. With a go library, the only thing that's required is a working go compiler...

And with the go compilers rather sweet support for easy cross-compiling, on many embedded systems, you don't need to install the go compiler ON the embedded device as such. And in the same vein, using go's cross compiler, setting up a pipeline (I'm currently using Azure) for delivering prebuilt binaries is a breeze, cross compiling C-code is, at least in my experience, much more of a PITA...

And perhaps the main reason: coapcmd is only intended as an alternative to the py3coap python extension for the domoticz IKEA-Tradfri plugin, which is a project I'm doing mainly for fun. And I find go to be much more fun to work with than C. I originally tried to create the python exstension using libcoap, but looking at the included examples, my eyes started watering over in trying to figure out how to construct a proper DTLS request. With go I was able to connect to the IKEA-tradfri gateway with relative ease...

With that said...

If there's enough interest, creating a API-layer for IKEA-Tradfri using the coap-client from libcoap as an alternative to coapcmd on embedded systems is quite easy, and I'm not adverse to implementing  it...

**Comment by axello** [comment]
Very valid points all. Thanks for the explanations. Did not know that GO has a good cross-compiler. Hence all the version you provide for different linux platforms. Sweet!
Don't worry for me implementing a bridge to the C library. coapcmd suffices.

I will close the issue now.
